### ISSUE TITLE
Chicory variability - extra text needed? - Bethan

### ISSUE THREAD

**Issue by amberfoam** [fo-am/sward-android-app#101]

**Comment by bethanstagg** [comment]
Is this ok or too long? 

Leaf: narrow oval, often lobed or toothed, often hairy, often pale green. Similar to dandelion when immature.

Perhaps this is a better image to use as it shows the slightly lobed vs toothed variation and hairy vs hairless

![image](https://user-images.githubusercontent.com/73833485/101477605-5c5d1f00-3947-11eb-8c38-703ac85fb387.png)
