### ISSUE TITLE
Description for playstore

### ISSUE THREAD

**Issue by amberfoam** [fo-am/sward-android-app#121]
This is the list at the moment - the first ten are the most important
I'll wait to hear whether to rework into a brief description 

Agriculture
Farming
Organic
Biodiverse
Regenerative
Sustainable
Grass
Pasture
Sward 
Ley

Multispecies
Agroecolog
Legume
Clover
Herb
Species-rich
 
Assuming we won't need these, as have captured single words from these phrases:

Grassland
Herbal ley
Diverse ley
Herbal pasture
Diverse pasture
Multispecies swards
Multi-species swards

**Comment by bethanstagg** [comment]
Drafts, will update once any feedback received

Multispecies Sward App

80-character description 
Guide to herbal/grassland ley species; sustainable, regenerative or organic agriculture.

4,000-character description
Guide to herbal/grassland ley species, featuring identification keys, a sward monitoring tool and comparison charts for herb, legume/clover and grass traits. Designed to assist beef/sheep/dairy farmers and land managers in the selection and monitoring of multispecies swards. Can be used to monitor Countryside Stewardship legume and herb-rich sward options (GS4). Diverse/species-rich pastures are an important part of sustainable, regenerative and organic agriculture.
The Multispecies Sward App has been created as part of the Toolbox of Multi-species Swards (TOMS) project, which is an information hub on the establishment and management of diverse leys. TOMS is funded through the  Agri-tech Cornwall and Isles of Scilly Project and is a partnership between Duchy College Rural Business School and Rothamsted Research North Wyke. The contribution of farmers, collaborating business partners, and other experts is gratefully acknowledged.

**Comment by nebogeo** [comment]
I put this on - the 80 char limit includes spaces so I took out "organic" for the moment... https://play.google.com/store/apps/details?id=am.fo.swardapp
