### ISSUE TITLE
Revise soil categories

### ISSUE THREAD

**Issue by bethanstagg** [fo-am/sward-android-app#122]
Is it possible to adjust the selection so that multiple soil categories can be selected?

Draft categories (Bethan to update following feedback)

Soil type (select 1 or more):
   Predominantly sandy
   Predominantly clay
   Predominantly silt
   Loam
   Organic/peat
   Shallow
   Stony
   Naturally wet/seasonally waterlogged

**Comment by nebogeo** [comment]
I think it might be too late/new feature to make this a multi selection as you can't use the same widget, so it needs a whole new layout - plus the export data will be different so there are knock-on complexities...

**Comment by bethanstagg** [comment]
Will it be ok to change the wording of the existing ones, if we keep to the same number?

________________________________

**Comment by nebogeo** [comment]
Yes & you can have as many as you like :)

**Comment by bethanstagg** [comment]
How many words will fit per category? These are the longest one for the new categories:
Light sandy or shallow soils over sandstone
Medium or shallow soils not over sandstone

**Comment by nebogeo** [comment]
This length will be fine...

**Comment by bethanstagg** [comment]
Here they are, finally (and short, as a bonus!)

Sandy or light silty
Medium (clay loams)
Heavy (clays)
Chalk or limestone
Peaty
