### ISSUE TITLE
Photo credits

### ISSUE THREAD

**Issue by bethanstagg** [fo-am/sward-android-app#128]
Credit Cotswold Seeds for plant images of meadow foxtail, meadow fescue, tall fescue
Credit Harry Rose for flower image of tall fescue

I've just realised I am not credited for the rest of the photos and, as my RBS contract finishes in 3 months, would be good to have my name somewhere on the app! What would be the best way - could a credit be added to the 'about us' text?
All photos taken by Bethan Stagg except where stated otherwise

**Comment by amberfoam** [comment]
Done on cards (all lower section of font dropped from size 10 to 9 to fit).
