### ISSUE TITLE
enhancement - address the issue  that some users get confused with 'agree/disagree'

### ISSUE THREAD

**Issue by bethanstagg** [fo-am/sward-android-app#136]
Rothamsted tester:
In Cock’s foot it has intensive grazed 3 studies agreed – yet it is still a thumbs down? 
Anthelminthic properties – 1 study agreed 0 studies disagreed – still a thumbs down 
Waterlogging tolerance  – 1 study agreed 0 studies disagreed – still a thumbs down 
Same issues as above (cocksfoot) for Meadow Fescue and persistence (grazed), relative yield, intensive cut, drought tolerance. I think the thumbs up/thumbs down criteria may need to be reviewed as it seems to differ per section and doesn’t seem to be consistent, but I am just a lay person so may have misunderstood.  Maybe as a novice, I'm not interpreting it the way it is intended, so perhaps it needs more explanation in the description section? It really isn’t clear that it was what the thumbs up and thumbs down bits are based on,

**Comment by nebogeo** [comment]
How about "From published literature (up to 2020), x studies agreed, y studies disagreed with this assessment."

**Comment by bethanstagg** [comment]
Yes, good idea.
I am copying in Gemma to check she is happy with that change.

________________________________

**Comment by bethanstagg** [comment]
Thanks for this, I think it would definitely help to add something at the end, although I'm just wondering if, as we refer to them as trait scores, it should read "...with this score"?

Gemma Eales
Research Leader
01579 372363
I am currently working from home
Please note, I work part-time (Monday-Wednesday)
www.swarmhub.co.uk/toolbox-of-multi-species-swards-toms/<http://www.swarmhub.co.uk/toolbox-of-multi-species-swards-toms/>

[ACP signature]<http://www.agritechcornwall.co.uk/>

Agri-tech Cornwall & the Isles of Scilly is a £11.8m project to increase Research Development and Innovation in the Agri-tech sector across Cornwall and the Isles of Scilly. Running to June 2021, it is part-funded by the European Regional Development Fund, Cornwall Council and the Council for the Isles of Scilly.

For more information, please see www.agritechcornwall.co.uk<http://www.agritechcornwall.co.uk/>


This email and any files with it are confidential and intended solely for the use of the recipient to whom it is addressed.  If you are not the intended recipient then:
*         Refrain from copying, distribution or other use of the information contained - it is strictly prohibited; and
*         Please let the sender know immediately and delete it from your system(s).

Internet emails are not necessarily secure or error-free.  You should check all emails and their attachments for signs of viruses.  While we take reasonable precautions, the Cornwall College Group (including Duchy College) accepts no liability for any damage caused by:
*         Any virus transmitted by this email; or
*         For any errors or omissions in the contents of this message, which arise as a result of e-mail transmission.

Nothing in this email or its attachments constitutes an order for goods or services unless accompanied by an official order form.

**Comment by bethanstagg** [comment]
ok

________________________________
From: Gemma Eales <gemma.eales@duchy.ac.uk>
Sent: 16 December 2020 13:05
To: Bethan Stagg <bethan.stagg@duchy.ac.uk>; fo-am/sward-android-app <reply@reply.github.com>
Subject: RE: [fo-am/sward-android-app] enhancement - address the issue that some users get confused with 'agree/disagree' (#136)


Thanks for this, I think it would definitely help to add something at the end, although I’m just wondering if, as we refer to them as trait scores, it should read “…with this score”?



Gemma Eales

Research Leader

01579 372363

I am currently working from home

Please note, I work part-time (Monday-Wednesday)

www.swarmhub.co.uk/toolbox-of-multi-species-swards-toms/<http://www.swarmhub.co.uk/toolbox-of-multi-species-swards-toms/>



[ACP signature]<http://www.agritechcornwall.co.uk/>



Agri-tech Cornwall & the Isles of Scilly is a £11.8m project to increase Research Development and Innovation in the Agri-tech sector across Cornwall and the Isles of Scilly. Running to June 2021, it is part-funded by the European Regional Development Fund, Cornwall Council and the Council for the Isles of Scilly.



For more information, please see www.agritechcornwall.co.uk<http://www.agritechcornwall.co.uk/>





This email and any files with it are confidential and intended solely for the use of the recipient to whom it is addressed.  If you are not the intended recipient then:

•         Refrain from copying, distribution or other use of the information contained – it is strictly prohibited; and

•         Please let the sender know immediately and delete it from your system(s).



Internet emails are not necessarily secure or error-free.  You should check all emails and their attachments for signs of viruses.  While we take reasonable precautions, the Cornwall College Group (including Duchy College) accepts no liability for any damage caused by:

•         Any virus transmitted by this email; or

•         For any errors or omissions in the contents of this message, which arise as a result of e-mail transmission.



Nothing in this email or its attachments constitutes an order for goods or services unless accompanied by an official order form.
