### ISSUE TITLE
Landing page image

### ISSUE THREAD

**Issue by bethanstagg** [fo-am/sward-android-app#57]
Photoshop out the plantain flower that sits on end of the word start?

**Comment by nebogeo** [comment]
I'd be a shame to lose it, and it doesn't really fix the problem (again it's dependent on screen geometry). I tried cropping the bottom of the image but it loses something of the composition, so I've made the text use up less space which hopefully looks ok - will be good to get feedback on these things via the workshop...

**Comment by bethanstagg** [comment]
Ok sounds good thanks

**Comment by nebogeo** [comment]
Closing this as it didn't come up as an issue in feedback - I've tweaked it so the image only appears in portrait mode as well, which helps with this.
