### ISSUE TITLE
How accessible is term 'species traits' 

### ISSUE THREAD

**Issue by bethanstagg** [fo-am/sward-android-app#58]
Am not convinced the term 'species traits' is accessible to farmers but not sure what is the best alternative term.
Could go for 'species attributes' - but that might present the same issue
'Species characteristics' is not a good alternative as this implies morphological characteristics eg height, seed size etc'
'Species features' not quite right either..

This also affects opening sentence of 'species info' to 'check the special traits and features of common sward species' 

Could be one to explore in the testing event

**Comment by nebogeo** [comment]
I think traits is ok if it's the word that you are using throughout your project, you can sort of claim it for this use and people will use it if there isn't a better one. The only thing I can think is changing it to "Beneficial species traits"?

**Comment by bethanstagg** [comment]
Sounds good
Maybe change 'check the special traits and features of common sward species' to 'check the beneficial species traits' in opening sentence of 'species info', or can await workshop feedback

**Comment by amberfoam** [comment]
Alex: thought was fine but 'qualities' might be better
