### ISSUE TITLE
Name for app

### ISSUE THREAD

**Issue by bethanstagg** [fo-am/sward-android-app#69]
Updating this for the workshop format:
We have reached consensus here on Multispecies Sward App, so it will be more of a case of checking if testers agree this is a good title (and if not, what suggestions they have). 'Sward selector' has the weakness that it does not indicate that the app is specific to multi species swards (implies it applies to conventional ones too). 'Diverse' is not used often enough to describe these type of swards to be a good option. Bethan

We need to decide the name for the app at the workshop. 
Proposals to date:
Multispecies Sward App
Sward selector app
Diverse sward selector app

Dave, could you label this 'workshop feedback needed', I can't work out how to? Thanks

**Comment by nebogeo** [comment]
(It's deceptively simple, and therefore a bit confusing - you just click on "labels" and select the label you want adding)

**Comment by bethanstagg** [comment]
Hi
Thanks Dave, I've just updated the comment for the workshops
________________________________

**Comment by bethanstagg** [comment]
Hi
Just added this issue but still can't figure out how to label it - the only reference to 'labels' seems to be on RHS where it says 'labels - none yet' but not clickable


3 people suggested a function under 'my farm' under 'add new field' to store a photo record of the sward, after selecting soil type, species etc.
Presumably this will need extra funds but flagging it up here so it can be added to the 'workshop feedback needed' list of topics

Bethan

________________________________
