### ISSUE TITLE
Menu and photo gallery 'dots' symbols

### ISSUE THREAD

**Issue by bethanstagg** [fo-am/sward-android-app#83]
Will people know the 3 vertical dots on top righthand corner means 'menu'
Will people know the green horizontal dots under photo means 'scroll through photo gallery'
(Steve)

**Comment by nebogeo** [comment]
We could change the splash screen text to indicate "top right menu" - the dots icon is the standard android menu one at least.
Above the photo dots It says "swipe left and right" - not sure how to make this more obvious without making it annoying.

**Comment by bethanstagg** [comment]
Yes adding 'top right menu' to splash screen text would do the trick
Ah yes, I never noticed those words above photo dots, let's leave that as it is
________________________________
