### ISSUE TITLE
Add privacy statement for data sharing

### ISSUE THREAD

**Issue by amberfoam** [fo-am/sward-android-app#96]

**Comment by bethanstagg** [comment]
DOWNLOAD YOUR DATA

 Enter an email address to send all data on your farm to yourself or someone else.

[Text box to enter an email address]

Researchers at Duchy College are interested in your data to understand how multispecies swards perform. Tick this box if you are happy to automatically send them your data for research purposes only.

 [Tick Box] I consent to sharing my farm data for research

 Information on this form will not be used for any other purpose, apart from research. If you would like your personal data removed in the future, please contact rbs@duchy.ac.uk. Duchy College is part of TCCG. For our privacy notice click here (hyperlink to https://www.cornwall.ac.uk/wp-content/uploads/2020/02/TCCG-Privacy-Notice-Commercial-Supplier-Organisation-v1.pdf)

With thanks for your help

**Comment by nebogeo** [comment]
This is done, and I also added the privacy statement to the play store listing
