### ISSUE TITLE
Add short sentence about how data will be used if shared?

### ISSUE THREAD

**Issue by amberfoam** [fo-am/sward-android-app#97]
Roughly what Bethan said:
Researchers are interested in which species are doing well depending on the soil type, and the persistence of different species over time... particularly in real farms rather than experimental setups

**Comment by nebogeo** [comment]
This might be good to have somewhere @bethanstagg - along with the legal bit maybe (and could be in the about) what you are interested in more specifically

**Comment by bethanstagg** [comment]
Change the following sentence on the 'download your data' page

Researchers at Duchy Rural Business School are interested in your data to understand how multispecies swards perform under different soil conditions over time.
